Repository DaedalusDock/daedalusdock, pull requests merged in 2022-10, with the labels that each got.

#43 Removes randomly disabled lighting
  code/game/area/areas.dm
Labels: hacktoberfest

#52 Fixes ZAS (again) (again) (again)
  code/modules/atmospherics/ZAS/Diagnostic.dm
  code/modules/atmospherics/ZAS/Turf.dm
  code/modules/atmospherics/ZAS/XGM/xgm_gas_mixture.dm
  code/modules/mob/living/simple_animal/hostile/tree.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/reagents/pyrotechnic_reagents.dm
Labels: bug, ZAS, KAPU MOMENT

#37 Couple goon sounds
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/humans.dm
  code/modules/mob/living/emote.dm
  code/modules/mob/living/living.dm
  goon/sounds/body_thud.ogg
  goon/sounds/voice/death_1.ogg
  goon/sounds/voice/death_2.ogg
  goon/sounds/voice/fescream1.ogg
  goon/sounds/voice/fescream5.ogg
  goon/sounds/voice/mascream4.ogg
  goon/sounds/voice/mascream5.ogg
  goon/sounds/voice/mascream7.ogg
Labels: hacktoberfest-accepted

#53 Ghosts not hearing sounds fix
  code/game/sound.dm
Labels: bug
