Repository DaedalusDock/daedalusdock, pull requests merged in 2023-05, with the labels that each got.

#275 GPL Mechanical Components (MechComp)
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/MetaStation/chemlab_holder.dmm
  code/__DEFINES/dcs/signals/signals_object.dm
  code/__DEFINES/logging.dm
  code/__DEFINES/mechcomp.dm
  code/__HELPERS/_logging.dm
  code/__HELPERS/spatial_info.dm
  code/_globalvars/logging.dm
  code/controllers/subsystem/codex.dm
  code/controllers/subsystem/packetnets.dm
  code/datums/mclink.dm
  code/game/area/areas/station.dm
  code/game/atoms.dm
  code/modules/codex/categories/mechcomp.dm
  code/modules/codex/entries/_codex_entry.dm
  code/modules/codex/entries/mechcomp.dm
  code/modules/mechcomp/_mc_interface.dm
  code/modules/mechcomp/_mc_message.dm
  code/modules/mechcomp/mcobjects/_mc_object.dm
  code/modules/mechcomp/mcobjects/graviton_accelerator.dm
  code/modules/mechcomp/mcobjects/led.dm
  code/modules/mechcomp/mcobjects/messaging/_messaging.dm
  code/modules/mechcomp/mcobjects/messaging/and.dm
  code/modules/mechcomp/mcobjects/messaging/arithmetic.dm
  code/modules/mechcomp/mcobjects/messaging/association.dm
  code/modules/mechcomp/mcobjects/messaging/button.dm
  code/modules/mechcomp/mcobjects/messaging/clock.dm
  code/modules/mechcomp/mcobjects/messaging/delay.dm
  code/modules/mechcomp/mcobjects/messaging/dispatch.dm
  code/modules/mechcomp/mcobjects/messaging/hand_scanner.dm
  code/modules/mechcomp/mcobjects/messaging/mc14500.dm
  code/modules/mechcomp/mcobjects/messaging/microphone.dm
  code/modules/mechcomp/mcobjects/messaging/or.dm
  code/modules/mechcomp/mcobjects/messaging/pressure_sensor.dm
  code/modules/mechcomp/mcobjects/messaging/radio_scanner.dm
  code/modules/mechcomp/mcobjects/messaging/regex_find.dm
  code/modules/mechcomp/mcobjects/messaging/regex_replace.dm
  code/modules/mechcomp/mcobjects/messaging/relay.dm
  code/modules/mechcomp/mcobjects/messaging/signal_builder.dm
  code/modules/mechcomp/mcobjects/messaging/signal_check.dm
  code/modules/mechcomp/mcobjects/messaging/ticker.dm
  code/modules/mechcomp/mcobjects/messaging/toggle.dm
  code/modules/mechcomp/mcobjects/messaging/wifi_split.dm
  code/modules/mechcomp/mcobjects/screen.dm
  code/modules/mechcomp/mcobjects/sound_synthesizer.dm
  code/modules/universal_states/resonance_jump.dm
  code/modules/vending/mechcomp.dm
  daedalus.dme
  goon/dummy.dme
  goon/icons/obj/mechcomp.dmi
  icons/area/areas_station.dmi
Labels: 515 OK

#316 Fix wall icons in mapmaking tools & hub entry length
  code/controllers/configuration/entries/general.dm
  code/game/turfs/closed/walls.dm
  code/game/world.dm
  config/config.txt
Labels: Config Update

#266 Lighting tweaks
  code/__DEFINES/colors.dm
  code/__DEFINES/mobs.dm
  code/game/machinery/camera/camera.dm
  code/game/machinery/computer/apc_control.dm
  code/game/machinery/dance_machine.dm
  code/game/machinery/status_display.dm
  code/game/objects/items/devices/flashlight.dm
  code/game/turfs/open/floor/light_floor.dm
  code/game/turfs/open/floor/misc_floor.dm
  code/modules/clothing/head/hardhat.dm
  code/modules/food_and_drinks/kitchen_machinery/microwave.dm
  code/modules/lighting/lighting_atom.dm
  code/modules/mapfluff/ruins/spaceruin_code/TheDerelict.dm
  code/modules/mining/equipment/marker_beacons.dm
  code/modules/mob/living/simple_animal/hostile/jungle/seedling.dm
  code/modules/mob/living/simple_animal/hostile/space_dragon.dm
  code/modules/modular_computers/computers/item/computer.dm
  code/modules/power/lighting/light_mapping_helpers.dm
  code/modules/power/monitor.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/projectiles/projectile/bullets/sniper.dm
Labels: 515 OK

#328 Atmos Fixes
  code/modules/atmospherics/machinery/components/binary_devices/circulator.dm
  code/modules/atmospherics/machinery/components/binary_devices/dp_vent_pump.dm
  code/modules/atmospherics/machinery/components/binary_devices/passive_gate.dm
  code/modules/atmospherics/machinery/components/binary_devices/pressure_valve.dm
  code/modules/atmospherics/machinery/components/binary_devices/pump.dm
  code/modules/atmospherics/machinery/components/binary_devices/temperature_gate.dm
  code/modules/atmospherics/machinery/components/trinary_devices/filter.dm
  code/modules/atmospherics/machinery/components/trinary_devices/mixer.dm
  code/modules/atmospherics/machinery/components/unary_devices/vent_pump.dm
  code/modules/atmospherics/machinery/datum_pipeline.dm
  code/modules/power/generator.dm
Labels: ZAS

#329 Automatic TGS DMAPI Update
  code/__DEFINES/tgs.dm
  code/modules/tgs/v3210/api.dm
Labels: Tools

#335 Automatic TGS DMAPI Update
  code/__DEFINES/tgs.dm
  code/modules/tgs/v4/api.dm
  code/modules/tgs/v5/api.dm
  code/modules/tgs/v5/bridge.dm
  code/modules/tgs/v5/topic.dm
Labels: Tools

#293 Improves MC Scheduling by not queueing subsystems without any work.
  code/__DEFINES/MC.dm
  code/__DEFINES/subsystems.dm
  code/_globalvars/bitfields.dm
  code/controllers/master.dm
  code/controllers/subsystem.dm
  code/controllers/subsystem/airflow.dm
  code/controllers/subsystem/ao.dm
  code/controllers/subsystem/asset_loading.dm
  code/controllers/subsystem/augury.dm
  code/controllers/subsystem/blackmarket.dm
  code/controllers/subsystem/circuit_component.dm
  code/controllers/subsystem/dbcore.dm
  code/controllers/subsystem/dcs.dm
  code/controllers/subsystem/explosions.dm
  code/controllers/subsystem/fire_burning.dm
  code/controllers/subsystem/icon_smooth.dm
  code/controllers/subsystem/lighting.dm
  code/controllers/subsystem/moods.dm
  code/controllers/subsystem/movement/ai_movement.dm
  code/controllers/subsystem/movement/movement.dm
  code/controllers/subsystem/movement/spacedrift.dm
  code/controllers/subsystem/packetnets.dm
  code/controllers/subsystem/processing/acid.dm
  code/controllers/subsystem/processing/ai_basic_avoidance.dm
  code/controllers/subsystem/processing/ai_behaviors.dm
  code/controllers/subsystem/processing/antag_hud.dm
  code/controllers/subsystem/processing/aura_healing.dm
  code/controllers/subsystem/processing/clock_component.dm
  code/controllers/subsystem/processing/conveyors.dm
  code/controllers/subsystem/processing/fluids.dm
  code/controllers/subsystem/processing/greyscale.dm
  code/controllers/subsystem/processing/instruments.dm
  code/controllers/subsystem/processing/obj_tab_items.dm
  code/controllers/subsystem/processing/processing.dm
  code/controllers/subsystem/processing/projectiles.dm
  code/controllers/subsystem/processing/quirks.dm
  code/controllers/subsystem/processing/reagents.dm
  code/controllers/subsystem/processing/singulo.dm
  code/controllers/subsystem/processing/station.dm
  code/controllers/subsystem/processing/wet_floors.dm
  code/controllers/subsystem/radiation.dm
  code/controllers/subsystem/throwing.dm
  code/controllers/subsystem/wardrobe.dm
  code/controllers/subsystem/zas.dm
Labels: 515 OK

#241 Griddle QoL changes + Spatula
  code/game/objects/items/kitchen.dm
  code/modules/food_and_drinks/kitchen_machinery/griddle.dm
  code/modules/food_and_drinks/plate.dm
  code/modules/research/designs/autolathe_designs.dm
  code/modules/vending/drinnerware.dm
  icons/mob/inhands/equipment/kitchen_lefthand.dmi
  icons/mob/inhands/equipment/kitchen_righthand.dmi
  icons/obj/kitchen.dmi
Labels: 515 OK

#346 Automatic TGS DMAPI Update
  code/__DEFINES/tgs.dm
  code/modules/tgs/v5/__interop_version.dm
Labels: Tools
