Repository DaedalusDock/daedalusdock, pull requests merged in 2023-08, with the labels that each got.

#479 Automatic TGS DMAPI Update
  code/modules/tgs/core/core.dm
  interface/interface.dm
Labels: Tools

#491 In-Game github Issue Reporter
  .gitignore
  code/controllers/configuration/entries/comms.dm
  code/modules/admin/sql_ban_system.dm
  config/comms.txt
  config/config.txt
  interface/interface.dm
Labels: Config Update

#139 Sealed Folders
  code/modules/paperwork/folders.dm
  icons/obj/bureaucracy.dmi
Labels: 515 OK

#506 Automatic TGS DMAPI Update
  code/__DEFINES/tgs.dm
Labels: Tools

#457 Remove New() uses in atmospherics equipment
  code/modules/atmospherics/machinery/components/binary_devices/circulator.dm
  code/modules/atmospherics/machinery/components/components_base.dm
  code/modules/atmospherics/machinery/components/trinary_devices/mixer.dm
  code/modules/atmospherics/machinery/components/unary_devices/portables_connector.dm
  code/modules/atmospherics/machinery/components/unary_devices/vent_pump.dm
  code/modules/atmospherics/machinery/components/unary_devices/vent_scrubber.dm
  code/modules/atmospherics/machinery/pipes/pipes.dm
Labels: Triaged
