Repository DaedalusDock/daedalusdock, pull requests merged in 2023-01, with the labels that each got.

#93 Space carp coloring changes + sprite changes
  code/datums/components/riding/riding_mob.dm
  code/modules/mob/living/simple_animal/hostile/carp.dm
  icons/effects/particles/sparkles.dmi
  icons/mob/carp.dmi
Labels: Spyro Being Based

#132 TGUI corners are now sharp by default
  tgui/packages/tgui/index.js
  tgui/packages/tgui/interfaces/PreferencesMenu/CharacterPreferenceWindow.tsx
  tgui/packages/tgui/styles/base.scss
  tgui/packages/tgui/styles/themes/rounded_base.scss
Labels: MY OPINIONS ARE ALWAYS RIGHT

#119 low effort initialize optimizations
  code/__DEFINES/flags.dm
  code/__DEFINES/icon_smoothing.dm
  code/__DEFINES/subsystems.dm
  code/__HELPERS/_lists.dm
  code/__HELPERS/level_traits.dm
  code/controllers/configuration/entries/general.dm
  code/controllers/subsystem/asset_loading.dm
  code/controllers/subsystem/assets.dm
  code/controllers/subsystem/early_assets.dm
  code/datums/elements/decals/_decal.dm
  code/datums/elements/strippable.dm
  code/game/area/space_station_13_areas.dm
  code/game/atoms.dm
  code/game/machinery/deployable.dm
  code/game/objects/effects/decals/cleanable/misc.dm
  code/game/objects/effects/decals/decal.dm
  code/game/objects/effects/decals/turfdecal/tilecoloring.dm
  code/game/objects/effects/spawners/structure.dm
  code/game/objects/items/storage/storage.dm
  code/game/objects/structures/aliens.dm
  code/game/objects/structures/false_walls.dm
  code/game/objects/structures/lattice.dm
  code/game/objects/structures/low_wall.dm
  code/game/objects/structures/window.dm
  code/game/turfs/closed/_closed.dm
  code/game/turfs/closed/minerals.dm
  code/game/turfs/closed/wall/mineral_walls.dm
  code/game/turfs/closed/walls.dm
  code/game/turfs/open/floor.dm
  code/game/turfs/open/grass.dm
  code/game/turfs/open/misc.dm
  code/game/turfs/turf.dm
  code/modules/asset_cache/asset_list.dm
  code/modules/capture_the_flag/_defines.dm
  code/modules/capture_the_flag/ctf_game.dm
  code/modules/capture_the_flag/ctf_map_loading.dm
  code/modules/capture_the_flag/ctf_panel.dm
  code/modules/capture_the_flag/ctf_voting.dm
  code/modules/client/preferences/assets.dm
  code/modules/industrial_lift/tram_walls.dm
  code/modules/mining/equipment/survival_pod.dm
  code/modules/plumbing/plumbers/pill_press.dm
  code/modules/reagents/chemistry/machinery/chem_master.dm
  code/modules/unit_tests/strippable.dm
  config/config.txt
  daedalus.dme
  tools/read_init_times.py
Labels: Config Update

#62 The Codex
  code/__DEFINES/subsystems.dm
  code/__DEFINES/text.dm
  code/controllers/subsystem/codex.dm
  code/game/atoms.dm
  code/modules/atmospherics/ZAS/XGM/gas_data.dm
  code/modules/atmospherics/machinery/portable/canister.dm
  code/modules/client/client_procs.dm
  code/modules/codex/categories/_codex_category.dm
  code/modules/codex/categories/categories.dm
  code/modules/codex/categories/gases.dm
  code/modules/codex/categories/guides.dm
  code/modules/codex/categories/uncategorized.dm
  code/modules/codex/codex_atom.dm
  code/modules/codex/codex_client.dm
  code/modules/codex/codex_mob.dm
  code/modules/codex/entries/_codex_entry.dm
  code/modules/codex/entries/atmospherics.dm
  code/modules/codex/entries/codex.dm
  code/modules/codex/entries/machinery.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/codex.dm
  daedalus.dme
  html/browser/common.css
Labels: enhancement

#123 [ATLAS] More work on Cargo
  _maps/_basemap.dm
  _maps/atlas.json
  _maps/map_files/Atlas/atlas.dmm
  code/_compile_options.dm
  code/datums/shuttles.dm
Labels: Atlas
