Repository DaedalusDock/daedalusdock, pull requests merged in 2023-04, with the labels that each got.

#223 Smaller bundle of upstream PRs
  code/datums/materials/alloys.dm
  code/game/objects/effects/decals/cleanable/misc.dm
  code/game/objects/effects/spawners/random/trash.dm
  code/game/objects/items/knives.dm
  code/game/objects/items/spear.dm
  code/game/objects/items/stacks/sheets/glass.dm
  code/game/objects/structures/window.dm
  code/game/turfs/open/floor.dm
  code/game/turfs/open/floor/plating.dm
  code/game/turfs/open/floor/reinforced_floor.dm
  code/modules/holodeck/computer.dm
  code/modules/mapping/mapping_helpers.dm
  daedalus.dme
  html/changelogs/clb-66544.yml
  html/changelogs/clb-71576.yml
  icons/mob/clothing/back.dmi
  icons/mob/inhands/weapons/melee_lefthand.dmi
  icons/mob/inhands/weapons/melee_righthand.dmi
  icons/mob/inhands/weapons/polearms_lefthand.dmi
  icons/mob/inhands/weapons/polearms_righthand.dmi
  icons/mob/inhands/weapons/swords_lefthand.dmi
  icons/mob/inhands/weapons/swords_righthand.dmi
  icons/obj/items_and_weapons.dmi
  icons/obj/shards.dmi
  icons/turf/floors.dmi
Labels: 515 OK

#287 Automatic TGS DMAPI Update
  code/__DEFINES/tgs.dm
  code/modules/tgs/README.md
  code/modules/tgs/core/README.md
  code/modules/tgs/core/datum.dm
  code/modules/tgs/includes.dm
  code/modules/tgs/v3210/api.dm
  code/modules/tgs/v3210/commands.dm
  code/modules/tgs/v4/api.dm
  code/modules/tgs/v4/commands.dm
  code/modules/tgs/v5/README.md
  code/modules/tgs/v5/__interop_version.dm
  code/modules/tgs/v5/_defines.dm
  code/modules/tgs/v5/api.dm
  code/modules/tgs/v5/commands.dm
  code/modules/tgs/v5/interop_version.dm
  code/modules/tgs/v5/serializers.dm
  code/modules/tgs/v5/undefs.dm
Labels: Tools

#265 Lizard Sclera & Hopefully fix hair
  code/__DEFINES/DNA.dm
  code/__HELPERS/dna.dm
  code/game/objects/items/cosmetics.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences/_preference.dm
  code/modules/client/preferences/species_features/basic.dm
  code/modules/client/preferences/species_features/moth.dm
  code/modules/client/preferences/species_features/vox.dm
  code/modules/clothing/head/wig.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
  code/modules/mob/living/carbon/human/species_types/mothmen.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/surgery/bodyparts/hair.dm
  code/modules/surgery/bodyparts/head.dm
  code/modules/surgery/bodyparts/species_parts/lizard_bodyparts.dm
  code/modules/surgery/organs/eyes.dm
  code/modules/unit_tests/screenshots/screenshot_humanoids__datum_species_lizard.png
  code/modules/unit_tests/screenshots/screenshot_humanoids__datum_species_lizard_ashwalker.png
  code/modules/unit_tests/screenshots/screenshot_humanoids__datum_species_lizard_silverscale.png
  icons/mob/human_face.dmi
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/species_features.tsx
Labels: 515 OK

#214 APC Base networking
  code/__DEFINES/packetnet.dm
  code/game/machinery/datanet/_networked.dm
  code/game/machinery/datanet/p2p_phones/_p2p_phones.dm
  code/game/objects/items/apc_frame.dm
  code/modules/power/apc/apc_main.dm
  code/modules/power/apc/apc_networking.dm
  code/modules/power/apc/apc_power_proc.dm
  code/modules/power/data_terminal.dm
  code/modules/power/terminal.dm
  daedalus.dme
Labels: 515 OK

#274 G.O.O.N. Presents: Blockmap Radio
  code/__DEFINES/important_recursive_contents.dm
  code/__DEFINES/spatial_gridmap.dm
  code/__DEFINES/traits.dm
  code/controllers/subsystem/packetnets.dm
  code/controllers/subsystem/spatial_gridmap.dm
  code/game/atoms_movable.dm
  code/game/communications.dm
  code/game/machinery/datanet/test_equipment/_test_equipment.dm
  code/game/machinery/datanet/test_equipment/test_equipment_radio.dm
  code/game/machinery/datanet/test_equipment/test_equipment_wired.dm
  code/game/objects/items/toys.dm
  daedalus.dme
Labels: 515 OK

#299 Automatic TGS DMAPI Update
  code/__DEFINES/tgs.dm
  code/modules/tgs/v5/api.dm
Labels: Tools

#289 Removes walls from GAGs
  code/__DEFINES/materials.dm
  code/datums/greyscale/config_types/greyscale_configs.dm
  code/datums/materials/_material.dm
  code/datums/materials/alloys.dm
  code/datums/materials/basemats.dm
  code/game/objects/structures/false_walls.dm
  code/game/objects/structures/low_wall.dm
  code/game/objects/structures/window.dm
  code/game/turfs/closed/walls.dm
  icons/turf/walls/wall_stripe.dmi
Labels: 515 OK

#288 The round starts with the crew arriving on the shuttle.
  code/__DEFINES/traits.dm
  code/controllers/subsystem/shuttle.dm
  code/datums/station_traits/negative_traits.dm
  code/game/area/areas/shuttles.dm
  code/game/gamemodes/objective.dm
  code/modules/antagonists/traitor/objectives/assassination.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/shuttle/arrivals.dm
  code/modules/shuttle/docking.dm
  code/modules/shuttle/on_move.dm
  code/modules/shuttle/shuttle.dm
  config/game_options.txt
Labels: Config Update, 515 OK

#308 Automatic TGS DMAPI Update
  code/__DEFINES/tgs.dm
  code/modules/tgs/includes.dm
  code/modules/tgs/v5/README.md
  code/modules/tgs/v5/__interop_version.dm
  code/modules/tgs/v5/_defines.dm
  code/modules/tgs/v5/api.dm
  code/modules/tgs/v5/bridge.dm
  code/modules/tgs/v5/chunking.dm
  code/modules/tgs/v5/commands.dm
  code/modules/tgs/v5/topic.dm
  code/modules/tgs/v5/undefs.dm
Labels: Tools

#313 Automatic TGS DMAPI Update
  code/__DEFINES/tgs.dm
  code/modules/tgs/v5/undefs.dm
Labels: Tools
