Repository DaedalusDock/daedalusdock, pull requests merged in 2025-04, with the labels that each got.

#1267 Moves cursors to the webpack bundle
  code/__HELPERS/html.dm
  code/datums/browser.dm
  code/modules/asset_cache/assets/cursors.dm
  code/modules/mob/dead/new_player/new_player_panel.dm
  code/modules/tgui_panel/tgui_panel.dm
  html/browser/common.css
  html/browser/cursors.css
  html/statbrowser.css
  tgui/global.d.ts
  tgui/packages/common/assets/default.cur
  tgui/packages/common/assets/link_select.cur
  tgui/packages/tgui-panel/styles/goon/chat-dark.scss
  tgui/packages/tgui-panel/styles/goon/chat-light.scss
  tgui/packages/tgui/styles/base.scss
  tgui/packages/tgui/styles/components/Button.scss
  tgui/packages/tgui/styles/reset.scss
  tgui/webpack.config.js
Labels: 516

#1280 Asystole gasping
  code/__DEFINES/cooldowns.dm
  code/__DEFINES/mobs.dm
  code/_globalvars/lists/keybindings.dm
  code/datums/datum.dm
  code/datums/emotes.dm
  code/datums/pathogens/advance/symptoms/choking.dm
  code/datums/pathogens/fake_gbs.dm
  code/datums/pathogens/gbs.dm
  code/datums/pathogens/rhumba_beat.dm
  code/datums/pathogens/tuberculosis.dm
  code/datums/status_effects/debuffs/debuffs.dm
  code/game/objects/items/defib.dm
  code/modules/aether/runes/revival_rune.dm
  code/modules/antagonists/vampire/vampire_states/vampire_wasting.dm
  code/modules/mob/emote.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/mob/living/emote.dm
  code/modules/mob/living/living.dm
  code/modules/mob/mob_defines.dm
  code/modules/surgery/organs/_organ.dm
  code/modules/surgery/organs/lungs.dm
Labels: Testmerge Candidate

#1287 Dormitories Restyling + Map Fixes
  _maps/map_files/Theseus/Theseus.dmm
Labels: Testmerge Candidate

#1297 Automatic TGS DMAPI Update
  code/__DEFINES/tgs.dm
  code/modules/tgs/v5/__interop_version.dm
  code/modules/tgs/v5/api.dm
Labels: Tools

#1303 Automatic TGS DMAPI Update
  code/__DEFINES/tgs.dm
  code/modules/tgs/v5/api.dm
Labels: Tools
